services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: ghcr.io/sunmh207/ai-codereview-gitlab:1.3.14
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./data:/app/data
      - ./log:/app/log
      - ./biz:/app/biz
      - ./conf:/app/conf
    env_file:
      - ./conf/.env
    restart: unless-stopped